apiVersion: v2
name: sample-app
description: A sample Helm chart for demonstrating the visualizer
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

